#include "ascii.h"

// The Fischer - Yates shuffle algorithm
static void shuffle(int *array, int n)
{
    srand(time(NULL));
    for (int i = n - 1; i > 0; i--)
    {
        int j = rand() % (i + 1);
        swap(&array[i], &array[j]);
    }
}

// Remove all ansi escape sequences from ansi picture
static char *get_clean_ascii(const char *source)
{
    int count = 0;
    size_t l = strlen(source);
    char c;
    char *clean = malloc(l);
    if (clean == NULL)
    {
        fprintf(stderr, "Can't allocate memory for 'clean'.\n");
        return NULL;
    }

    // Skip the first 2 escape sequences (generated by jp2a)
    int position = 10;

    c = ansi_pic[position];

    // Clean the string from all escape sequences
    while (c != '\0' && (count + 10) < (int)l)
    {
        if (c == '\n' && (count + 10) < (int)l)
        {
            position++;
        }
        clean[count++] = ansi_pic[position++];
        c = ansi_pic[position];
    }

    clean[count] = '\0'; // Null termination

    // The caller of the function hast to free the allocated memory !
    return clean;
}

int main()
{
    int shuffle_index, shuffled_row, shuffled_col, row, col, total_pixels;
    bool is_end = false;
    char pic_array[MAXY][MAXX] = {{0}};

    // Get a clean string without escape sequences, just printable chars
    char *clean = get_clean_ascii(ansi_pic);
    if (clean == NULL)
    {
        fprintf(stderr, "Error cleaning ansi_pic.\n");
        return 1;
    }

    row = 0;
    col = 0;

    // count rows, columns and store clean picture in 2D array
    for (int i = 0; i < (int)strlen(clean); i++)
    {
        if (i % WIDTH == 0)
        {
            row++;
            col = 0;
        }
        pic_array[row][col++] = clean[i];
    }
    // Free the allocated memory from 'get_clean_ascii' function
    free(clean);

    // Delete screen and go to position 1, 1
    printf(CLRJ);

    total_pixels = row * col;
    int shuffle_array[total_pixels];

    // Fill the shuffle array with ascending numbers.
    for (int i = 0; i < total_pixels; i++)
    {
        shuffle_array[i] = i;
    }

    // Shuffle all the numbers in the array
    shuffle(shuffle_array, total_pixels);

    // Set text mode: Yellow bold
    printf(YELLOW);

    // Hide the cursor
    printf(INVISIBLE);

    // Show and delete the picture with amazing shuffle effect
    for (int p = 0; p < 2; p++)
    {
        for (int i = 0; i < total_pixels; i++)
        {
            shuffle_index = shuffle_array[i];
            shuffled_row = shuffle_index / col;
            shuffled_col = shuffle_index % col;

            printf("\033[%d;%dH", shuffled_row + 1, shuffled_col + 1);
            printf("%c", pic_array[shuffled_row][shuffled_col]);
            usleep(SPEED);
            fflush(stdout);
        }

        // Show the ASCII art for 2 seconds at first glance
        !is_end ? (sleep(2), is_end = true) : 0;
        
        // Shuffle the array again for deletion effect
        shuffle(shuffle_array, total_pixels);
        
        // Delete the 2D array (Fill with blank spaces)
        for (int r = 0; r < MAXX; r++)
        {
            for (int q = 0; q < MAXY; q++)
                pic_array[r][q] = ' ';
        }
    }

    // Reset text mode
    printf(RST);

    // Delete screen and go to position 1, 1
    printf(CLRJ);

    // Show the cursor again
    printf(VISIBLE);

    return 0;
}
